### ISSUE TITLE
Sponsor Logos

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/api#22]
We somehow need to integrate sponsor logos.

We could either store them as binary image data in the database (ideally in a separate table linked to the sponsors table), or just store an URL to the logo somewhere else.

External logos are subject to network problems though and we can't control the image format, so I think I'd prefer storing the logos in the database. I don't think we'll ever have that many logos that we'll run into performance issues.

(@rnestler maybe you also have a comment regarding this issue.)

**Comment by schmijos** [comment]
I'm normally agains storing images in the database because it's harder to stream them over the network (by for example not using sendfile). But attaching a persistent storage other than the database (docker container for static files or cloud storage) only for the logos seems overkill to me. So I'd go for the blob solution for now.

**Comment by dbrgn** [comment]
Yeah, it's certainly not ideal, but probably perfectly fine in practice :) And we can do caching on the client side.

**Comment by schmijos** [comment]
Should be implemented with #39

**Comment by dbrgn** [comment]
This is now finally merged and deployed!

**Comment by schmijos** [comment]
Lol, after 3 years. It's done in https://github.com/gfroerli/api/pull/70 btw. (not https://github.com/gfroerli/api/pull/39).

**Comment by dbrgn** [comment]
![image](https://user-images.githubusercontent.com/105168/110546439-c1830500-812e-11eb-9ebc-9ce8aec20805.png)

💪🏻
